repos:
  - repo: local
    hooks:
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black -S --line-length 120 # -S - skip string normalization
        language: python
        types: [ python ]

      - id: ruff
        name: ruff
        entry: ruff check --fix
        language: python
        types: [ python ]
        args: [
          "--config",
          "format.quote-style = 'single'",
          "--config", 
          "line-length = 120"
        ]

      # - id: mypy
      #   name: mypy
      #   entry: mypy --exclude '\.venv|venv' --install-types --ignore-missing-imports --explicit-package-bases  -v
      #   language: python
      #   types: [ python ] 

      - id: clean_py
        name: ./clean-py.sh
        entry: ./clean-py.sh
        language: system