services:
  nginx:
    profiles: ["require__nginx"]
    container_name: nginx
    image: nginx:latest
    depends_on:
      auth_service:
        condition: service_started
      admin_panel:
        condition: service_started            
      movies_service:
        condition: service_started    
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/configs:/etc/nginx/conf.d:ro
      - ../nginx/static:/data/static:ro
    ports:
      - "80:80"
    env_file:
      - ${ENV_FILE}